package com.diabdata.models

enum class MedicalDeviceInfoType() {
    WIRELESS_PATCH,
    WIRED_PATCH,
    CONTINUOUS_GLUCOSE_MONITORING_SYSTEM_SENSOR,
    CONTINUOUS_GLUCOSE_MONITORING_SYSTEM_TRANSMITTER,
    WIRELESS_PATCH_REMOTE,
    WIRED_PUMP
}