name: DiabData build and test
run-name: Build & Test - ${{ github.ref_name }}
on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
jobs:
  Diabdata-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Install Java 21 temurin JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Configure gradle caching
        uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - name: Build project
        run: ./gradlew assembleDebug
      - name: Compilation tests
        run: ./gradlew test